### ISSUE TITLE
Does not work on Windows 11

### ISSUE THREAD

**Issue by amirasyraf** [V0l-D/Discord-Netflix#52]
OS: Windows 11 Pro
Version: 22H2
OS Build: 22621.674
Experience: Windows Feature Experience Pack 1000.22634.1000.0

Discord-Netflix Version: Latest release, v1.0.8

Problem: Only shows 'Browsing' 'In The Catalogs'. Does not update when playing any video. I've tried multiple videos, closing and then reopening Netflix. I've also tried waiting for a while, e.g. 5+ minutes and rich presence is still not updated

![image](https://user-images.githubusercontent.com/15522007/199653163-6282a06e-8676-4eb1-a961-2c563068a869.png)

**Comment by V0l-D** [comment]
Best thing would be to contact me on Discord, I currently use Discord-Netflix on the insider preview version of Windows 11 with no issues.

**Comment by V0l-D** [comment]
Seeing that it has been solved and it was only a one time incident I will close the issue.
